### ISSUE TITLE
Marshal sets

### ISSUE THREAD

**Issue by cyli** [rackerlabs/silverberg#53]
https://github.com/rackerlabs/silverberg/pull/43 Kindly added support for unmarshalling sets, but marshalling the same format doesn't seem to work.

When I execute the query:

`INSERT INTO <tablename> (<set_column>) VALUES (:val)`, with parameters `{"val" = set([1, 2, 3, 4])}`

I get the following exception: 

`silverberg.cassandra.ttypes.InvalidRequestException: InvalidRequestException(why="line 1:76 extraneous input ']' expecting ')'")`

But when I execute the query 

`INSERT INTO <tablename> (<set_column>) VALUES ({1, 2, 3, 4})`, with parameters `{}`

That works fine.

**Comment by cyli** [comment]
When this is fixed, https://github.com/rackerlabs/silverberg/pull/54/files#diff-17eb52e28e7c3632c86d249d423daf12R217 should probably be removed.

**Comment by TimothyZhang** [comment]
hi @cyli, this is because set type is not correctly marshalled. I have created a new pull request #55 about that. Please take a review. Sorry for the trouble.

**Comment by cyli** [comment]
Hi @TimothyZhang!  There is a way to convert GitHub issues into pull requests using [hub](http://codeinthehole.com/writing/converting-github-issues-into-pull-requests/), but [it is deprecated](https://github.com/github/hub/commit/4f70dd126f46dec14fc341c97c18efae417743c7).

Totally fine to just make a new pull request, and just add "Fixes #53" to the description.  :)  That will close this issue once that pull request gets merged.

Thank you so much for all your contributions and your quick response time!

**Comment by cyli** [comment]
Closed by #55
